/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import Classes.ClsConexion;
//import Classes.clsFunciones;
//import Classes.clsProducto;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Wilmer S A
 */
public class frmbuscarProducto extends javax.swing.JInternalFrame {
//      clsFunciones funciones = new clsFunciones();
//    clsProducto RegistrosProductos = new clsProducto();
    String Fila[];
    int id;
   // int idProducto= funciones.getmiIDProducto();
    DefaultTableModel DatosTablaLocal;
    private TableRowSorter trsfiltro;

   String titulos[]={"ID","NOMBRE","MARCA","STOCK","PRECIO"};
    /**
     * Creates new form buscarProveedor
     */
    public frmbuscarProducto() {
        initComponents();
            DatosTablaLocal = new DefaultTableModel(null,titulos);
        dlglistado.setModel(DatosTablaLocal);
        GrupoBotones.add(rdbID);
         GrupoBotones.add(rdbNombre);
         GrupoBotones.add(rdbMarca);
        MostrarTotalProducto();
        
    }
     public void filtro() {
    //Obtenemos el valor del JTextField para el filtro
    String filtro = TxtCodigo1.getText();
    // Identificamos cual es el JRadioButton seleccionado para filtrar el
    // resultado de acuerdo a los datos de la columna elegida
    if (rdbID.isSelected()) {
        int columna = 0;
        trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
    } else if (rdbNombre.isSelected()) {
        int columna = 1;
        trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
    } else if (rdbMarca.isSelected()) {
        int columna = 2;
        trsfiltro.setRowFilter(RowFilter.regexFilter(filtro, columna));
    }
}
    
    public void MostrarTotalProducto(){
//        Connection cn;
//        Statement sentencia;
//        ResultSet reg;
//        String SQL;
//
//        
//        try {
//            SQL = "Select * from producto where estado=1";
//            cn = ClsConexion.getConexion();
//            sentencia = cn.createStatement();
//            reg=sentencia.executeQuery(SQL);
//            //VERIFICAR SI HA DEVUELTO REGISTROS
//              while(reg.next()){
//                  
//                
//                  String Fila[]= {
//                                        reg.getString("id"),
//                                        reg.getString("nombre"),
//                                        reg.getString("marca"),
//                                        reg.getString("stock"),
//                                        reg.getString("precio")};
//                  DatosTablaLocal.addRow(Fila);
//              }
//                  
//                 
//              
//            
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage().toString());
//
//            
//        }
//    
    }
 
   public void VaciarTabla(){
        int Filas=DatosTablaLocal.getRowCount();
        for (int i = 0; i < Filas; i++) {
            DatosTablaLocal.removeRow(0);
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotones = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TxtCodigo1 = new javax.swing.JTextField();
        BtnCerrarP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dlglistado = new javax.swing.JTable();
        BtnRegistrarP1 = new javax.swing.JButton();
        rdbMarca = new javax.swing.JRadioButton();
        rdbNombre = new javax.swing.JRadioButton();
        rdbID = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Proveedor");

        jPanel5.setBackground(new java.awt.Color(0, 25, 66));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel19.setText("Proveedor");

        TxtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigo1ActionPerformed(evt);
            }
        });
        TxtCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCodigo1KeyTyped(evt);
            }
        });

        BtnCerrarP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCerrarP.setText("Cerrar");
        BtnCerrarP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnCerrarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrarP.setIconTextGap(-3);
        BtnCerrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarPActionPerformed(evt);
            }
        });

        dlglistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dlglistado);

        BtnRegistrarP1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnRegistrarP1.setText("Aceptar");
        BtnRegistrarP1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnRegistrarP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegistrarP1.setIconTextGap(-3);
        BtnRegistrarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarP1ActionPerformed(evt);
            }
        });

        rdbMarca.setText("MARCA");

        rdbNombre.setText("NOMBRE");

        rdbID.setText("ID");

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel18.setText("Filtrar resultados por : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRegistrarP1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(BtnCerrarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbID)
                        .addGap(18, 18, 18)
                        .addComponent(rdbNombre)
                        .addGap(18, 18, 18)
                        .addComponent(rdbMarca))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rdbID)
                    .addComponent(rdbNombre)
                    .addComponent(rdbMarca))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TxtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(BtnRegistrarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnCerrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigo1ActionPerformed

    private void BtnCerrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarPActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnCerrarPActionPerformed

    private void BtnRegistrarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarP1ActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel DatosTabla = (DefaultTableModel)RegistrarVenta11.dlgventas.getModel();
//        int infila = dlglistado.getSelectedRow();
//        if(infila >=0){
//            int codProductoH= Integer.parseInt(dlglistado.getValueAt(infila,0).toString());
//            RegistrarVenta11.TxtCodigoProducto.setText(codProductoH+"");
//        }
    }//GEN-LAST:event_BtnRegistrarP1ActionPerformed

    private void TxtCodigo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigo1KeyTyped
        // TODO add your handling code here:
         // Comprobamos que el ButtonGroup que nosotros llamamos bGfiltar tenga
    // seleccionado alguno de los tres JRadioButtons que le hemos agregado
    if (GrupoBotones.getSelection()==null) {
        // Si ninguno de los JRadioButtons está seleccionado, evitamos que se
        // escriba algo dentro del JTextField y mostramos un mensaje de error
        evt.consume();
        JOptionPane.showMessageDialog(this, "Debe seleccionar una opción del filtro", "Menaje de Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Añadimos al JTextField un KeyListener con un KeyAdapter. De esta
        // forma es como si dieramos enter cada vez que digitamos una techa
        TxtCodigo1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(final KeyEvent e) {
                // Llamamos al método encargado de realizar el filtro
                filtro();
            }
        });
        // Inicializamos el objeto trsfiltro de la clase TableRowSorter con
        // el modelo de la tabla, que para nuestro caso es tabladatos
        trsfiltro = new TableRowSorter(DatosTablaLocal);
        // Añadimos al Jtable el filtro trsfiltro
        dlglistado.setRowSorter(trsfiltro);
    }
    }//GEN-LAST:event_TxtCodigo1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarP;
    private javax.swing.JButton BtnRegistrarP1;
    private javax.swing.ButtonGroup GrupoBotones;
    private javax.swing.JTextField TxtCodigo1;
    private javax.swing.JTable dlglistado;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbID;
    private javax.swing.JRadioButton rdbMarca;
    private javax.swing.JRadioButton rdbNombre;
    // End of variables declaration//GEN-END:variables
}
