/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import Classes.ClsConexion;
//import Classes.clsFunciones;
//import Classes.clsVenta;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KELLY TG
 */
public class frmDetalleCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleCompra
     */
//    clsFunciones funciones = new clsFunciones();
//    clsVenta venta= new clsVenta();
    String titulos[]={"NUMERO","RUC","FECHA","SUBTOTAL","IGV","TOTAL"};
    DefaultTableModel DatosTabla;
    public frmDetalleCompra() {
        initComponents();
         DatosTabla = new DefaultTableModel(null,titulos){
            @Override 
            public  boolean isCellEditable ( int row ,  int column )  { 
                return  false ; 
            } 
        };
        tblListado.setModel(DatosTabla);
//        MostrarTabla();
        RealizarCuenta();
    }
//    public boolean validarDateFecha(){
//        if(dateFechaDesde.getDate()==null) return false;
//        else if(dateFechaHasta.getDate()==null) return false;
//        else return true;
//    }
            
 public void VaciarTabla(){
        int Filas=DatosTabla.getRowCount();
        for (int i = 0; i < Filas; i++) {
            DatosTabla.removeRow(0);
        }
      }
     private void RealizarCuenta(){
        String IGVS,SUBTOTALS,TOTALS;
        float subtotal,IGV,total;
        float Ssubtotal=0,SIGV=0,Stotal=0;
        for (int i = 0; i < DatosTabla.getRowCount(); i++) {
            IGVS=(String) tblListado.getValueAt(i, 4);
            SUBTOTALS=(String) tblListado.getValueAt(i, 3);
            TOTALS=(String) tblListado.getValueAt(i, 5);
            
            
            IGV=Float.parseFloat(IGVS);
            subtotal=Float.parseFloat(SUBTOTALS);
            total=Float.parseFloat(TOTALS);
            
            SIGV+=IGV;
            Ssubtotal+=subtotal;
            Stotal+=total;
        }
        txtsubtotal.setText(String.valueOf(Ssubtotal));
        txtIGV.setText(String.valueOf(SIGV));
        txttotal.setText(String.valueOf(Stotal));

    }
    
//     private  void MostrarTabla(){
//        Connection cn;
//        Statement sentencia;
//        ResultSet reg;
//        String SQL;
//        String msj;
//
//        
//        try {
//            SQL="SELECT *FROM compra ORDER BY fecha DESC " ;
//           
//            cn = ClsConexion.getConexion();
//            sentencia = cn.createStatement();
//            reg=sentencia.executeQuery(SQL);
//            //VERIFICAR SI HA DEVUELTO REGISTROS
//              while(reg.next()){
//                  
//                  String Fila[]= {
//                                        reg.getString("serie")+"-"+reg.getString("numero"),
//                                        
//                                        reg.getString("ruc"),
//                                        reg.getString("fecha"),
//                                        reg.getString("subTotal"),
//                                        reg.getString("igv"),
//                                        
//                                        reg.getString("total")
//                                        //new JButton("Click")
//                                         };
//                  DatosTabla.addRow(Fila);
//              }
//        } catch (Exception e) {
//            
//            msj = e.getMessage().toString();
//            JOptionPane.showMessageDialog(this, msj);
//            
//        }
//        
//        
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtsubtotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtIGV = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnMostraarP = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Detalle compra");

        jPanel1.setBackground(new java.awt.Color(0, 25, 66));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtsubtotal.setEditable(false);
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListado);

        jLabel24.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel24.setText("FECHA");

        jLabel28.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel28.setText("SUB-TOTAL:");

        txtIGV.setEditable(false);
        txtIGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIGVActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel29.setText("IGV:");

        jLabel30.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel30.setText("TOTAL:");

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel25.setText("Desde:");

        jLabel26.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel26.setText("Hasta:");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMostraarP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMostraarP.setText("MOSTRAR PRODUCTOS");
        btnMostraarP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMostraarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostraarP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel25)))
                .addGap(166, 166, 166)
                .addComponent(jLabel26)
                .addGap(199, 199, 199)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel25))
                    .addComponent(jLabel26)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostraarP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostraarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraarPActionPerformed
        // TODO add your handling code here:
//        int nFila= tblListado.getSelectedRow();
//        if(nFila>=0){
//            String idCompra;
//            int idcompra,idventa;
//            idCompra=(String) tblListado.getValueAt(nFila, 0);
//           
//            String compraarray[]=idCompra.split("-");
//            idcompra=venta.BuscarIDcompraxSeriexNum(compraarray[1], compraarray[0]);
//            
//            
//            //idcompra=Integer.parseInt(idCompra);
//            //idventa=venta.BuscarIDcompra(idcompra);
//            funciones.setmiIDcompra(idcompra);
//
//            ProductosCompra Pro=new ProductosCompra();
//            FrmPrincipal.bpnPrinicipal.add(Pro);
//            Pro.toFront();
//            Pro.setVisible(true);
//
//        }
    }//GEN-LAST:event_btnMostraarPActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
//        if(validarDateFecha()){
//        Connection cn;
//        Statement sentencia;
//        ResultSet reg;
//        String SQL;
//        String msj;
//        VaciarTabla();
//        String fecha = new SimpleDateFormat("yyyy/MM/dd").format(dateFechaDesde.getDate());
//        String fecha2 = new SimpleDateFormat("yyyy/MM/dd").format(dateFechaHasta.getDate());
//        try {
//            SQL="SELECT *FROM compra where fecha>='" + fecha+ "' AND fecha<'" + fecha2 + "' + interval 1 day ORDER BY fecha DESC" ;
//
//            cn = ClsConexion.getConexion();
//            sentencia = cn.createStatement();
//            reg=sentencia.executeQuery(SQL);
//            //VERIFICAR SI HA DEVUELTO REGISTROS
//            while(reg.next()){
//               
//                String Fila[]= {
//                    reg.getString("serie")+"-"+reg.getString("numero"),
//                    
//                    reg.getString("ruc"),
//                    reg.getString("fecha"),
//                     reg.getString("subTotal"),
//                    reg.getString("igv"),
//                   
//                    reg.getString("total")
//                    //new JButton("Click")
//                };
//                DatosTabla.addRow(Fila);
//            }
//            RealizarCuenta();
//        } catch (Exception e) {
//
//            msj = e.getMessage().toString();
//            JOptionPane.showMessageDialog(this, msj);
//
//        }
//        }else JOptionPane.showMessageDialog(this,"INGRESE LA FECHA");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtIGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIGVActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostraarP;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
