/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author KELLY TG
 */
public class frmProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarProveedor
     */
    String ultimo;
    //clsFunciones funciones = new clsFunciones();
    //clsRegistros registros = new clsRegistros();
        
    public frmProveedor() {
        initComponents();
        SoloNumeros(txtRUC);
        SoloNumerosGuion(txtNumCuenta);
        SoloNumeros(TxtTelefono1);
        Limite(txtRUC,11);
        DesactivarCampos();
    }
    
    public void SoloLetras(JTextField a){
        a.addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent e){
               char c=e.getKeyChar();
               if((c<=64 || c>=91) && (c<=96 || c>=123) && c!=32){
                   getToolkit().beep();
                   e.consume();
               }
           }
                   
        });
    }
 public void Limite(final JTextField a,final int lim){
        a.addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent e){
               if(a.getText().length()==lim){
                   getToolkit().beep();
                   e.consume();
               }
           }         
        });
    }
 public void SoloNumeros(JTextField a){
        a.addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent e){
               char c=e.getKeyChar();
               if(!Character.isDigit(c)){
                   getToolkit().beep();
                   e.consume();
               }
           }
                   
        });
    }
 
 public void SoloNumerosGuion(JTextField a){
        a.addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent e){
               char c=e.getKeyChar();
               if(!Character.isDigit(c) && c!=45){
                   getToolkit().beep();
                   e.consume();
               }
           }
                   
        });
    }
 
 public boolean validarProveedor(){
     if(txtRazon.getText().equals("")) return false;
     else if(TxtDireccion1.getText().equals("")) return false;
     else if(TxtTelefono1.getText().equals("")) return false;
     else if(TxtEmail1.getText().equals("")) return false;
     else if(txtNumCuenta.getText().equals("")) return false;
     else return true;
 }
    
    public void LimparCampos(){
        txtRUC.setText("");
        TxtDireccion1.setText("");
        TxtEmail1.setText("");
        TxtTelefono1.setText("");
        txtNumCuenta.setText("");
        txtRazon.setText("");
    }
    public void DesactivarCampos(){
 
        TxtDireccion1.setEnabled(false);
        TxtEmail1.setEnabled(false);
        TxtTelefono1.setEnabled(false);
        txtNumCuenta.setEnabled(false);
        txtRazon.setEnabled(false);
        BtnRegistrar5.setEnabled(false);
    }
    public void ActivarCampos(){

        TxtDireccion1.setEnabled(true);
        TxtEmail1.setEnabled(true);
        TxtTelefono1.setEnabled(true);
        txtNumCuenta.setEnabled(true);
        txtRazon.setEnabled(true);
        BtnRegistrar5.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRazon = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxtDireccion1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtTelefono1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtEmail1 = new javax.swing.JTextField();
        txtNumCuenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BtnRegistrar5 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Proveedor");

        jPanel1.setBackground(new java.awt.Color(0, 25, 66));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel12.setText("RUC:");

        jLabel13.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel13.setText("Razón Social: ");

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel18.setText("Direccion:");

        jLabel19.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel19.setText("Telefono:");

        jLabel20.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel20.setText("E-mail:");

        jLabel14.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel14.setText("N° de Cuenta:");

        BtnRegistrar5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnRegistrar5.setText("REGISTRAR");
        BtnRegistrar5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnRegistrar5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnRegistrar5.setIconTextGap(-3);
        BtnRegistrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrar5ActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.setIconTextGap(-3);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEmail1))
                            .addComponent(TxtDireccion1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(70, 70, 70)
                                .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnRegistrar5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(TxtDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(TxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(BtnRegistrar5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrar5ActionPerformed
        // TODO add your handling code here:
       
//      if(validarProveedor()){
//            String msj[]=registros.RegistrarProveedor(txtRUC.getText(), txtRazon.getText(), TxtDireccion1.getText(),
//                TxtTelefono1.getText(), txtNumCuenta.getText(), TxtEmail1.getText());
//            
//       if(msj[1].equals("1")){
//            ultimo = funciones.UltimoRegistro("id", "proveedor");
// 
//            JOptionPane.showMessageDialog(this,msj[0]);
//            LimparCampos();
//            DesactivarCampos();
//       }else
//       {
//           JOptionPane.showMessageDialog(this,msj[0]);
//       }
//      } else JOptionPane.showMessageDialog(this,"LLENE TODOS LOS CAMPOS");
        
    }//GEN-LAST:event_BtnRegistrar5ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
//        String consulta[]=registros.BuscarProveedor(txtRUC.getText());
//        if(txtRUC.getText().equals("")){
//            JOptionPane.showMessageDialog(this,"Llene el campo del RUC");
//        }
//            else{
//
//
//            if(consulta[1].equals("1")){
//                JOptionPane.showMessageDialog(this,consulta[0]);
//
//            }
//                else{
//
//                    if(consulta[1].equals("2")){
//                       JOptionPane.showMessageDialog(this,consulta[0]);
//                       ActivarCampos();
//
//                    }
//                    else{
//                        JOptionPane.showMessageDialog(this,consulta[0]);
//                    }
//                }
//            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar5;
    private javax.swing.JTextField TxtDireccion1;
    private javax.swing.JTextField TxtEmail1;
    private javax.swing.JTextField TxtTelefono1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtRazon;
    // End of variables declaration//GEN-END:variables
}
