/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import Classes.clsFunciones;
//import Classes.clsUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author KELLY TG
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
//    clsFunciones funciones = new clsFunciones();
//    int id= funciones.getIDUsaurio();
//     clsUsuario usuario = new clsUsuario();
    public frmPrincipal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
 
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
                
            }
        });
         //DesactivarMenu();
        //ValidarOpciones();
    }
    private void close(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
             //System.exit(0);
             Login login = new Login();
             this.setVisible(false);
             login.setVisible(true);
        }
           
    }
    
    public void DesactivarMenu(){
        menucompras.setEnabled(false);
        menuventas.setEnabled(false);
        menualmacen.setEnabled(false);
        menuinformes.setEnabled(false);
        menuadministracion.setEnabled(false);
    }
    public void ValidarOpciones(){
//        int accesos[]=usuario.MostrarAccesos(id);
//                if(accesos[0]==1) menucompras.setEnabled(true);
//                if(accesos[1]==1) menuventas.setEnabled(true);
//                if(accesos[2]==1) menucaja.setEnabled(true);
//                if(accesos[3]==1) menualmacen.setEnabled(true);
//                if(accesos[4]==1) menuinformes.setEnabled(true);
//                if(accesos[5]==1) menumantenimiento.setEnabled(true);
//                if(accesos[6]==1) menuadministracion.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu29 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuBar12 = new javax.swing.JMenuBar();
        jMenu45 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuBar13 = new javax.swing.JMenuBar();
        jMenu47 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        bpnPrinicipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucompras = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuventas = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menualmacen = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jSeparator33 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator34 = new javax.swing.JPopupMenu.Separator();
        jMenuItem37 = new javax.swing.JMenuItem();
        jSeparator35 = new javax.swing.JPopupMenu.Separator();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        jMenuItem38 = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        jSeparator29 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator30 = new javax.swing.JPopupMenu.Separator();
        menuinformes = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jSeparator51 = new javax.swing.JPopupMenu.Separator();
        jMenuItem30 = new javax.swing.JMenuItem();
        jSeparator52 = new javax.swing.JPopupMenu.Separator();
        menuadministracion = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jSeparator63 = new javax.swing.JPopupMenu.Separator();
        jMenuItem41 = new javax.swing.JMenuItem();
        jSeparator64 = new javax.swing.JPopupMenu.Separator();
        jMenuItem42 = new javax.swing.JMenuItem();
        jSeparator65 = new javax.swing.JPopupMenu.Separator();
        jSeparator62 = new javax.swing.JPopupMenu.Separator();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenu15.setText("File");
        jMenuBar5.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar5.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar6.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar6.add(jMenu18);

        jMenu14.setText("File");
        jMenuBar7.add(jMenu14);

        jMenu19.setText("Edit");
        jMenuBar7.add(jMenu19);

        jMenu21.setText("File");
        jMenuBar8.add(jMenu21);

        jMenu22.setText("Edit");
        jMenuBar8.add(jMenu22);

        jMenu23.setText("File");
        jMenuBar9.add(jMenu23);

        jMenu24.setText("Edit");
        jMenuBar9.add(jMenu24);

        jMenu25.setText("File");
        jMenuBar10.add(jMenu25);

        jMenu26.setText("Edit");
        jMenuBar10.add(jMenu26);

        jMenu27.setText("jMenu27");

        jMenu28.setText("jMenu28");

        jMenu29.setText("File");
        jMenuBar11.add(jMenu29);

        jMenu30.setText("Edit");
        jMenuBar11.add(jMenu30);

        jMenu33.setText("jMenu33");

        jMenuItem40.setText("jMenuItem40");

        jMenuItem46.setText("jMenuItem46");

        jMenuItem48.setText("jMenuItem48");

        jMenu45.setText("File");
        jMenuBar12.add(jMenu45);

        jMenu46.setText("Edit");
        jMenuBar12.add(jMenu46);

        jMenuItem60.setText("jMenuItem60");

        jMenu47.setText("File");
        jMenuBar13.add(jMenu47);

        jMenu48.setText("Edit");
        jMenuBar13.add(jMenu48);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menucompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregarCompra.png"))); // NOI18N
        menucompras.setText("Compras");

        jMenu31.setText("Proveedor");

        jMenuItem20.setText("Registrar");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu31.add(jMenuItem20);
        jMenu31.add(jSeparator13);

        jMenuItem21.setText("Lista");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu31.add(jMenuItem21);
        jMenu31.add(jSeparator14);

        jMenuItem22.setText("Modificar");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu31.add(jMenuItem22);

        menucompras.add(jMenu31);
        menucompras.add(jSeparator5);

        jMenuItem4.setText("Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menucompras.add(jMenuItem4);
        menucompras.add(jSeparator6);
        menucompras.add(jSeparator1);

        jMenuBar1.add(menucompras);

        menuventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Usuarios.png"))); // NOI18N
        menuventas.setText("Ventas");
        menuventas.add(jSeparator3);

        jMenuItem11.setText("Venta");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuventas.add(jMenuItem11);
        menuventas.add(jSeparator10);

        jMenuBar1.add(menuventas);

        menualmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Modificar.png"))); // NOI18N
        menualmacen.setText("Almacen");

        jMenu34.setText("Producto");

        jMenuItem34.setText("Registrar Categoria");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu34.add(jMenuItem34);
        jMenu34.add(jSeparator33);

        jMenuItem14.setText("Registrar Producto");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu34.add(jMenuItem14);
        jMenu34.add(jSeparator34);

        jMenuItem37.setText("Modificar Producto");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu34.add(jMenuItem37);
        jMenu34.add(jSeparator35);

        menualmacen.add(jMenu34);
        menualmacen.add(jSeparator27);

        jMenuItem38.setText("Lista de Productos");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        menualmacen.add(jMenuItem38);
        menualmacen.add(jSeparator28);
        menualmacen.add(jSeparator29);

        jMenu1.setText("Existencias");

        jMenuItem6.setText("Registrar Existencia");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem19.setText("Modificar Existencia");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem19);

        menualmacen.add(jMenu1);
        menualmacen.add(jSeparator30);

        jMenuBar1.add(menualmacen);

        menuinformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modfCant.png"))); // NOI18N
        menuinformes.setText("Informes");

        jMenuItem29.setText("Detalle Compra");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        menuinformes.add(jMenuItem29);
        menuinformes.add(jSeparator51);

        jMenuItem30.setText("Detalle Venta");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        menuinformes.add(jMenuItem30);
        menuinformes.add(jSeparator52);

        jMenuBar1.add(menuinformes);

        menuadministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cliente.png"))); // NOI18N
        menuadministracion.setText("Administrador");

        jMenu35.setText("Usuario");

        jMenuItem36.setText("Registrar");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu35.add(jMenuItem36);
        jMenu35.add(jSeparator63);

        jMenuItem41.setText("Modificar");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu35.add(jMenuItem41);
        jMenu35.add(jSeparator64);

        jMenuItem42.setText("Eliminar");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu35.add(jMenuItem42);
        jMenu35.add(jSeparator65);

        menuadministracion.add(jMenu35);
        menuadministracion.add(jSeparator62);

        jMenuBar1.add(menuadministracion);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bpnPrinicipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bpnPrinicipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
  frmModificarUsuario proveedor = new frmModificarUsuario();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
  frmDetalleCompra proveedor = new frmDetalleCompra();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
  frmDetalleVenta proveedor = new frmDetalleVenta();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        frmRegistrarUsuario proveedor = new frmRegistrarUsuario();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        // TODO add your handling code here:
  frmEliminarUsuario proveedor = new frmEliminarUsuario();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:
     
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
  frmModificarExistencias proveedor = new frmModificarExistencias();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        frmRegistrarExistencias proveedor = new frmRegistrarExistencias();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
    frmListadoProductos proveedor = new frmListadoProductos();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
  frmModificarProducto proveedor = new frmModificarProducto();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
  frmProducto proveedor = new frmProducto();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
  frmCategoria proveedor = new frmCategoria();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
  frmRegistrarCompra proveedor = new frmRegistrarCompra();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
  frmModificarProveedor proveedor = new frmModificarProveedor();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        frmListaProveedor proveedor = new frmListaProveedor();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        frmProveedor proveedor = new frmProveedor();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        frmRegistrarVenta proveedor = new frmRegistrarVenta();  //crear el nuevo formulario
                boolean mostrar=true;
        
                    for (int a=0;a<bpnPrinicipal.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
                            if( proveedor.getClass().isInstance( bpnPrinicipal.getComponent(a) )){
                                   mostrar=false;
                                }
                        }
                    if(mostrar){
                            int x=(bpnPrinicipal.getWidth()/2) - proveedor.getWidth()/2;
                            int y=(bpnPrinicipal.getHeight()/2) - proveedor.getHeight()/2;
                            proveedor.setLocation(x, y);
                            bpnPrinicipal.add(proveedor);
                            proveedor.show();
                        }         // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane bpnPrinicipal;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar12;
    private javax.swing.JMenuBar jMenuBar13;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JPopupMenu.Separator jSeparator29;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator30;
    private javax.swing.JPopupMenu.Separator jSeparator33;
    private javax.swing.JPopupMenu.Separator jSeparator34;
    private javax.swing.JPopupMenu.Separator jSeparator35;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator51;
    private javax.swing.JPopupMenu.Separator jSeparator52;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator62;
    private javax.swing.JPopupMenu.Separator jSeparator63;
    private javax.swing.JPopupMenu.Separator jSeparator64;
    private javax.swing.JPopupMenu.Separator jSeparator65;
    private javax.swing.JMenu menuadministracion;
    private javax.swing.JMenu menualmacen;
    private javax.swing.JMenu menucompras;
    private javax.swing.JMenu menuinformes;
    private javax.swing.JMenu menuventas;
    // End of variables declaration//GEN-END:variables
}
